### ISSUE TITLE
Mejorar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-ifuenteromero#1]
super buen trabajo @ifuenteromero !!

Algunas pistas para mejorarlo:

- [x] Mueve el `li` fuera del componente 'Pokemon', de esta manera Pokemon es un componente con una tarjeta que podemos usar en diferentes sitios y no solo dentro de un `ul`
- [x] Añade un título a la página (Mi lista de Pokemons)
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by ifuenteromero** [comment]
Hi @nasivuela  I think it's done. Thanks for your time and your knowledge

**Comment by nasivuela** [comment]
Excelente!

Cierro issue, pero te dejo una ultima recomendación. Aunque el id coincida con el indice del array, intenta evitar transformar el id en indice (-1) para localizar el item en el array. Esto lo haces dos veces, una en el handler del click de favoritos y otra en la pagina de detalle. Sería mejor si buscaras en el array el item cuyo id coincide con el id que tienes.

![](https://media.giphy.com/media/2Uy3Lu0hmGO8D6l7kk/giphy.gif)
